package model

// User represents the user entity in the system.
// It includes JSON tags for correct serialization/deserialization to/from snake_case.
type User struct {
	ID        int64  `json:"id"`         // User ID, auto-generated by the database
	Name      string `json:"name"`       // Full name of the user, required
	CreatedAt int64  `json:"created_at"` // Timestamp of user creation in microseconds
	UpdatedAt int64  `json:"updated_at"` // Timestamp of last update in microseconds
}
